name: Run Python Tests
on:
  push:
    branches:
      - development
      - main
      - testing
  pull_request:
    branches:
      - development
      - main
      - testing

jobs:
  windows_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r requirements.txt
          pip install -e .
          pip install pytest pytest-qt
      - name: List packages
        run: pip list
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check --output-format=github --select=E9,F63,F7,F82 --target-version=py37 .
      - name: Run tests with pytest
        run: pytest -v
  ubuntu_test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          sudo apt install libgl1 libglx-mesa0 libegl1 libopengl0 libpulse0
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r requirements.txt
          pip install -e .
          pip install pytest pytest-qt pytest-xvfb
          export QT_DEBUG_PLUGINS=1
      - name: List packages
        run: pip list
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check --output-format=github --select=E9,F63,F7,F82 --target-version=py37 .
      - name: Run tests with pytest
        run: pytest -v
  macos_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          brew install hdf5
          echo "HDF5_DIR=$(brew --prefix hdf5)" >> $GITHUB_ENV
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r requirements.txt
          pip install -e .
          pip install pytest pytest-qt
      - name: List packages
        run: pip list
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check --output-format=github --select=E9,F63,F7,F82 --target-version=py37 .
      - name: Run tests with pytest
        run: pytest -v